"""Task runner. `python tasks.py <command>`

Deliberately not a Makefile: `make` is absent on stock Windows, and an evaluator
hitting a missing `make` at step one would break the under-15-minute promise
before it started. See docs/decision_log.md D11.

Run `python tasks.py` with no arguments to list commands.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
VENV_PY = REPO_ROOT / ".venv" / ("Scripts" if sys.platform == "win32" else "bin") / (
    "python.exe" if sys.platform == "win32" else "python"
)


def _py() -> str:
    """Prefer the venv interpreter so tasks work whether or not it is activated."""
    return str(VENV_PY) if VENV_PY.exists() else sys.executable


def _run(*args: str, check: bool = True) -> int:
    printable = " ".join(str(a) for a in args)
    print(f"\n$ {printable}\n", flush=True)
    t0 = time.perf_counter()
    rc = subprocess.run([str(a) for a in args]).returncode
    dt = time.perf_counter() - t0
    print(f"\n[{'ok' if rc == 0 else 'FAIL'}] {dt:.1f}s  ({printable})", flush=True)
    if check and rc != 0:
        raise SystemExit(rc)
    return rc


# ---------------------------------------------------------------------------
# commands
# ---------------------------------------------------------------------------

def cmd_setup(_: argparse.Namespace) -> None:
    """Install core dependencies into the venv and make src/ importable."""
    _run(_py(), "-m", "pip", "install", "--upgrade", "pip", "setuptools", "wheel")
    _run(_py(), "-m", "pip", "install", "-r", "requirements.in")
    _run(_py(), "-m", "pip", "install", "-e", ".")
    print(
        "\nNext: `python tasks.py lock` to freeze exact versions into "
        "requirements.txt (see decision_log.md D18)."
    )


def cmd_setup_embed(_: argparse.Namespace) -> None:
    """Install the OPTIONAL embedding deps (torch, ~200MB). Only needed to
    rebuild embeddings from scratch — not to reproduce reported numbers."""
    _run(_py(), "-m", "pip", "install", "-r", "requirements-embed.txt")


def cmd_lock(_: argparse.Namespace) -> None:
    """Freeze the resolved environment into requirements.txt."""
    out = subprocess.run(
        [_py(), "-m", "pip", "freeze"], capture_output=True, text=True, check=True
    ).stdout
    header = (
        "# GENERATED by `python tasks.py lock` — do not hand-edit.\n"
        "# Source of truth for what to install is requirements.in.\n"
        "# This lock is platform-specific (Windows / CPython 3.12). See D18.\n"
    )
    # Drop the editable self-reference; `pip install -e .` handles it.
    lines = [ln for ln in out.splitlines() if "threadpilot" not in ln.lower()]
    (REPO_ROOT / "requirements.txt").write_text(
        header + "\n".join(lines) + "\n", encoding="utf-8", newline="\n"
    )
    print(f"wrote requirements.txt ({len(lines)} pinned packages)")


def cmd_check(_: argparse.Namespace) -> None:
    """Verify the environment: imports, config, credentials, data presence."""
    _run(_py(), "-m", "threadpilot.check")


def cmd_data(args: argparse.Namespace) -> None:
    """Download the raw Kaggle dataset (~500MB, one time)."""
    extra = ["--force"] if getattr(args, "force", False) else []
    _run(_py(), "scripts/download_data.py", *extra)


def cmd_subsample(_: argparse.Namespace) -> None:
    """Build the committed, seeded brand subsample."""
    _run(_py(), "scripts/build_subsample.py")


def cmd_test(_: argparse.Namespace) -> None:
    """Run the test suite (includes the golden/index leakage guard)."""
    _run(_py(), "-m", "pytest")


def cmd_eval(args: argparse.Namespace) -> None:
    """Regenerate every number in docs/report.md.

    --offline replays the committed LLM cache and needs NO API key. A cache
    miss in offline mode is a hard error, never a silent fallback (D10).
    """
    extra: list[str] = []
    if getattr(args, "offline", False):
        extra.append("--offline")
    if getattr(args, "no_cache", False):
        extra.append("--no-cache")
    _run(_py(), "-m", "eval.run_eval", *extra)


def cmd_repro(_: argparse.Namespace) -> None:
    """Phase 9: the timed path an evaluator follows. Offline, no API key."""
    t0 = time.perf_counter()
    cmd_check(argparse.Namespace())
    _run(_py(), "-m", "pytest")
    _run(_py(), "-m", "eval.run_eval", "--offline")
    print(f"\n=== total wall clock: {time.perf_counter() - t0:.1f}s ===")
    print("The under-15-minute claim in the README refers to this number.")


def cmd_clean(_: argparse.Namespace) -> None:
    """Remove regenerable artifacts. Never touches raw data or committed caches."""
    for rel in ("data/interim", ".pytest_cache", ".ruff_cache"):
        p = REPO_ROOT / rel
        if p.exists():
            shutil.rmtree(p, ignore_errors=True)
            print(f"removed {rel}")
    for pyc in REPO_ROOT.rglob("__pycache__"):
        shutil.rmtree(pyc, ignore_errors=True)
    print("done (raw data, golden set and LLM cache left intact)")


COMMANDS = {
    "setup": cmd_setup,
    "setup-embed": cmd_setup_embed,
    "lock": cmd_lock,
    "check": cmd_check,
    "data": cmd_data,
    "subsample": cmd_subsample,
    "test": cmd_test,
    "eval": cmd_eval,
    "repro": cmd_repro,
    "clean": cmd_clean,
}


def main() -> int:
    ap = argparse.ArgumentParser(
        prog="tasks.py",
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="commands:\n"
        + "\n".join(
            f"  {name:<13} {(fn.__doc__ or '').strip().splitlines()[0]}"
            for name, fn in COMMANDS.items()
        ),
    )
    ap.add_argument("command", nargs="?", choices=list(COMMANDS))
    ap.add_argument("--offline", action="store_true",
                    help="eval: replay the committed LLM cache, no API key needed")
    ap.add_argument("--no-cache", action="store_true",
                    help="eval: force live API calls, ignoring the cache")
    ap.add_argument("--force", action="store_true",
                    help="data: re-download even if the CSV is already present")
    args = ap.parse_args()

    if not args.command:
        ap.print_help()
        return 0
    COMMANDS[args.command](args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
